# Generated by Django 5.1.5 on 2025-03-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='service',
        ),
    ]
