# Generated by Django 5.1.5 on 2025-03-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('service_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cliente.client')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
