# Generated by Django 5.2 on 2025-04-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='next_service',
            field=models.DateField(blank=True, null=True),
        ),
    ]
